use testkyc;
create table Person (
   ID   INT IDENTITY(1,1),
   FULL_NAME VARCHAR (30) NOT NULL,
   FATH_NAME VARCHAR (30) NOT NULL,
   MOTH_NAME VARCHAR (30) NOT NULL,
   DOB DATE NOT NULL,
   PAN_NO VARCHAR (10) NOT NULL,
   GENDER VARCHAR (10) NOT NULL,
   MARITAL VARCHAR (25) NOT NULL,
   CITIZENSHIP VARCHAR (25) NOT NULL,
   RESIDENT VARCHAR (25) NOT NULL,
   OCCUPY VARCHAR (25) NOT NULL,
   PRIMARY KEY (ID)
);